-- AlterTable
ALTER TABLE "cubematch_scores" ADD COLUMN     "accuracy_rate" DOUBLE PRECISION,
ADD COLUMN     "additions_count" INTEGER,
ADD COLUMN     "additions_score" INTEGER,
ADD COLUMN     "assist_enabled" BOOLEAN,
ADD COLUMN     "average_move_time_ms" INTEGER,
ADD COLUMN     "breaks_taken" INTEGER,
ADD COLUMN     "cells_cleared" INTEGER,
ADD COLUMN     "combo_max" INTEGER,
ADD COLUMN     "difficulty_adjustments" INTEGER,
ADD COLUMN     "difficulty_level" TEXT,
ADD COLUMN     "divisions_count" INTEGER,
ADD COLUMN     "divisions_score" INTEGER,
ADD COLUMN     "engagement_score" DOUBLE PRECISION,
ADD COLUMN     "failed_moves" INTEGER,
ADD COLUMN     "fastest_move_time_ms" INTEGER,
ADD COLUMN     "focus_time_percentage" DOUBLE PRECISION,
ADD COLUMN     "game_duration_seconds" INTEGER,
ADD COLUMN     "game_mode" TEXT,
ADD COLUMN     "grid_completion_rate" DOUBLE PRECISION,
ADD COLUMN     "grid_size_cols" INTEGER,
ADD COLUMN     "grid_size_rows" INTEGER,
ADD COLUMN     "hints_enabled" BOOLEAN,
ADD COLUMN     "hints_used" INTEGER,
ADD COLUMN     "longest_combo_chain" INTEGER,
ADD COLUMN     "max_consecutive_hits" INTEGER,
ADD COLUMN     "max_consecutive_misses" INTEGER,
ADD COLUMN     "max_size" INTEGER,
ADD COLUMN     "multiplications_count" INTEGER,
ADD COLUMN     "multiplications_score" INTEGER,
ADD COLUMN     "operator_sequence" TEXT,
ADD COLUMN     "session_end_time" TIMESTAMP(3),
ADD COLUMN     "session_start_time" TIMESTAMP(3),
ADD COLUMN     "slowest_move_time_ms" INTEGER,
ADD COLUMN     "sound_enabled" BOOLEAN,
ADD COLUMN     "spawn_rate_max" INTEGER,
ADD COLUMN     "spawn_rate_min" INTEGER,
ADD COLUMN     "subtractions_count" INTEGER,
ADD COLUMN     "subtractions_score" INTEGER,
ADD COLUMN     "successful_moves" INTEGER,
ADD COLUMN     "target_numbers_used" TEXT,
ADD COLUMN     "theme_used" TEXT,
ADD COLUMN     "tick_ms" INTEGER,
ADD COLUMN     "time_spent_on_additions_ms" INTEGER,
ADD COLUMN     "time_spent_on_divisions_ms" INTEGER,
ADD COLUMN     "time_spent_on_multiplications_ms" INTEGER,
ADD COLUMN     "time_spent_on_subtractions_ms" INTEGER,
ADD COLUMN     "total_break_time_ms" INTEGER,
ADD COLUMN     "total_moves" INTEGER;
