-- AlterTable
ALTER TABLE "cubematch_scores" ALTER COLUMN "accuracy_rate" SET DEFAULT 0,
ALTER COLUMN "additions_count" SET DEFAULT 0,
ALTER COLUMN "additions_score" SET DEFAULT 0,
ALTER COLUMN "assist_enabled" SET DEFAULT true,
ALTER COLUMN "average_move_time_ms" SET DEFAULT 0,
ALTER COLUMN "breaks_taken" SET DEFAULT 0,
ALTER COLUMN "cells_cleared" SET DEFAULT 0,
ALTER COLUMN "combo_max" SET DEFAULT 0,
ALTER COLUMN "difficulty_adjustments" SET DEFAULT 0,
ALTER COLUMN "difficulty_level" SET DEFAULT 'normal',
ALTER COLUMN "divisions_count" SET DEFAULT 0,
ALTER COLUMN "divisions_score" SET DEFAULT 0,
ALTER COLUMN "engagement_score" SET DEFAULT 0,
ALTER COLUMN "failed_moves" SET DEFAULT 0,
ALTER COLUMN "fastest_move_time_ms" SET DEFAULT 0,
ALTER COLUMN "focus_time_percentage" SET DEFAULT 0,
ALTER COLUMN "game_duration_seconds" SET DEFAULT 0,
ALTER COLUMN "game_mode" SET DEFAULT 'classic',
ALTER COLUMN "grid_completion_rate" SET DEFAULT 0,
ALTER COLUMN "grid_size_cols" SET DEFAULT 10,
ALTER COLUMN "grid_size_rows" SET DEFAULT 10,
ALTER COLUMN "hints_enabled" SET DEFAULT true,
ALTER COLUMN "hints_used" SET DEFAULT 0,
ALTER COLUMN "longest_combo_chain" SET DEFAULT 0,
ALTER COLUMN "max_consecutive_hits" SET DEFAULT 0,
ALTER COLUMN "max_consecutive_misses" SET DEFAULT 0,
ALTER COLUMN "max_size" SET DEFAULT 9,
ALTER COLUMN "multiplications_count" SET DEFAULT 0,
ALTER COLUMN "multiplications_score" SET DEFAULT 0,
ALTER COLUMN "slowest_move_time_ms" SET DEFAULT 0,
ALTER COLUMN "sound_enabled" SET DEFAULT true,
ALTER COLUMN "spawn_rate_max" SET DEFAULT 5,
ALTER COLUMN "spawn_rate_min" SET DEFAULT 3,
ALTER COLUMN "subtractions_count" SET DEFAULT 0,
ALTER COLUMN "subtractions_score" SET DEFAULT 0,
ALTER COLUMN "successful_moves" SET DEFAULT 0,
ALTER COLUMN "theme_used" SET DEFAULT 'classic',
ALTER COLUMN "tick_ms" SET DEFAULT 12000,
ALTER COLUMN "time_spent_on_additions_ms" SET DEFAULT 0,
ALTER COLUMN "time_spent_on_additions_ms" SET DATA TYPE BIGINT,
ALTER COLUMN "time_spent_on_divisions_ms" SET DEFAULT 0,
ALTER COLUMN "time_spent_on_divisions_ms" SET DATA TYPE BIGINT,
ALTER COLUMN "time_spent_on_multiplications_ms" SET DEFAULT 0,
ALTER COLUMN "time_spent_on_multiplications_ms" SET DATA TYPE BIGINT,
ALTER COLUMN "time_spent_on_subtractions_ms" SET DEFAULT 0,
ALTER COLUMN "time_spent_on_subtractions_ms" SET DATA TYPE BIGINT,
ALTER COLUMN "total_break_time_ms" SET DEFAULT 0,
ALTER COLUMN "total_break_time_ms" SET DATA TYPE BIGINT,
ALTER COLUMN "total_moves" SET DEFAULT 0;
